// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Change Theme Color', async function() {
    await driver.get("http://localhost:3000/dashboard")
    await driver.findElement(By.css(".fa-cog")).click()
    await driver.findElement(By.xpath("(//input[@value=\'\'])[2]")).click()
    await driver.findElement(By.xpath("//div[@id=\'settings\']/div[3]/ul/div/div[2]/div/button[6]")).click()
    await driver.findElement(By.xpath("//div[@id=\'settings\']/div[3]/ul/div/div[3]/div/button[5]")).click()
  })
  it('Test Navigation', async function() {
    await driver.get("http://localhost:3000/dashboard")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[2]/div[2]/span")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[3]")).click()
    {
      const element = await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[4]/div[2]/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[4]/div[2]/span")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[5]/div[2]/span")).click()
    {
      const element = await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[6]/div[2]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[6]/div[2]")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a[7]/div[2]/span")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/div/ul[2]/a/div[2]/span")).click()
  })
})
